#+FILETAGS: ACADEMIC

* Seminars
** DONE Seminars org project
   - State "DONE"       from "TODO"       [2012-10-18 Thu 11:13]
  CLOCK: [2012-10-14 Sun 20:38]--[2012-10-14 Sun 20:38] =>  0:00
[2012-10-14 Sun 20:38]
** TODO Invite Visitors
Some money available through colloquia funds?
  CLOCK: [2012-10-14 Sun 20:39]--[2012-10-14 Sun 20:40] =>  0:01
[2012-10-14 Sun 20:39]
* Grants
* Students
** TODO Research Supervising
Say summer projects, or reading courses
Can I employ (through a grant?) research assistants? These should get something like a paper or conference proceeding out of it

  CLOCK: [2012-10-15 Mon 09:32]--[2012-10-15 Mon 09:33] =>  0:01
[2012-10-15 Mon 09:32]
* Assistants
* Research
** TODO Write tutorials on project management, GTD so on for mathematicians, scientists, academics and teachers
** TODO Research grants
I want mostly travel money 
Can I hire a car so we can all go on a road trip?
I need books
I want to do some sage or org-mode devel
I want to do teaching with sage-tex and/or org-mode with babel; i.e. interactive lectures so I can change the parameters of things like plots in real time
  CLOCK: [2012-10-14 Sun 20:40]--[2012-10-14 Sun 20:41] =>  0:01
[2012-10-14 Sun 20:40]
** TODO Preparing/doing research using org-mode
Write a paper on how to do it? Use my own paper preperation as model
  CLOCK: [2012-10-14 Sun 20:42]--[2012-10-14 Sun 20:43] =>  0:01
[2012-10-14 Sun 20:42]
* Reviews
* Tasks
** TODO Contact Ben Andrews about MCF, geometric evolution eqn's books
  CLOCK: [2012-10-17 Wed 08:23]--[2012-10-17 Wed 08:23] =>  0:00
[2012-10-17 Wed 08:23]
* Notes
