#+LAST_MOBILE_CHANGE: 2013-01-24 15:55:55









































* Body was changed in MobileOrg and on the computer F(edit:body) [[id:d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9][Give talk on Brendle's proof of Lawson conjecture]]
  :PROPERTIES:
  :ID:       930d8f49-02c2-4f5a-a570-3dc51729004f
  :END:
** Old value
:LOGBOOK:
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** New value
:LOGBOOK:
CLOCK: [2013-01-29 Tue 15:18]--[2013-01-29 Tue 16:37] =>  1:18
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** End of edit


* Body was changed in MobileOrg and on the computer F(edit:body) [[id:d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9][Give talk on Brendle's proof of Lawson conjecture]]
  :PROPERTIES:
  :ID:       754b374b-da30-42d7-97b4-a4673c74abad
  :END:
** Old value
:LOGBOOK:
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** New value
:LOGBOOK:
CLOCK: [2013-01-29 Tue 18:52]--[2013-01-29 Tue 19:53] =>  1:01
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** End of edit

