#+LAST_MOBILE_CHANGE: 2013-01-24 15:55:55









































* Body was changed in MobileOrg and on the computer F(edit:body) [[id:d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9][Give talk on Brendle's proof of Lawson conjecture]]
  :PROPERTIES:
  :ID:       930d8f49-02c2-4f5a-a570-3dc51729004f
  :END:
** Old value
:LOGBOOK:
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** New value
:LOGBOOK:
CLOCK: [2013-01-29 Tue 15:18]--[2013-01-29 Tue 16:37] =>  1:18
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** End of edit


* Body was changed in MobileOrg and on the computer F(edit:body) [[id:d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9][Give talk on Brendle's proof of Lawson conjecture]]
  :PROPERTIES:
  :ID:       754b374b-da30-42d7-97b4-a4673c74abad
  :END:
** Old value
:LOGBOOK:
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** New value
:LOGBOOK:
CLOCK: [2013-01-29 Tue 18:52]--[2013-01-29 Tue 19:53] =>  1:01
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** End of edit



* Body was changed in MobileOrg and on the computer F(edit:body) [[id:d52c3978-eea8-457c-b9c9-1a38d6d54a88][High Intensity]]
  :PROPERTIES:
  :ID:       1dd2ebd7-7a0b-4032-9394-a1c789513a9a
  :END:
** Old value
SCHEDULED: <2013-01-30 Wed .+4d/5d>
    - State "DONE"       from "NEXT"       [2013-01-26 Sat 18:10]
    - State "DONE"       from "NEXT"       [2013-01-22 Tue 19:24]
    - State "CANCELLED"  from "NEXT"       [2013-01-15 Tue 09:55] \\
      Sick
    - State "DONE"       from "NEXT"       [2013-01-12 Sat 16:23]
    - State "CANCELLED"  from "NEXT"       [2013-01-07 Mon 12:58] \\
      Too much pain.
    - State "DONE"       from "NEXT"       [2012-12-29 Sat 11:47]
    - State "DONE"       from "NEXT"       [2012-12-25 Tue 12:22]
    - State "DONE"       from "NEXT"       [2012-12-19 Wed 12:35]
    - State "DONE"       from "NEXT"       [2012-12-15 Sat 17:35]
    - State "DONE"       from "NEXT"       [2012-12-10 Mon 18:04]
    - State "CANCELLED"  from "NEXT"       [2012-12-06 Thu 09:56] \\
      Was too tired
    - State "DONE"       from "NEXT"       [2012-12-02 Sun 19:47]
    - State "DONE"       from "NEXT"       [2012-11-22 Thu 10:34]
    - State "DONE"       from "NEXT"       [2012-11-18 Sun 09:59]
:LOGBOOK:
CLOCK: [2012-12-29 Sat 11:10]--[2012-12-29 Sat 11:35] =>  0:24
CLOCK: [2012-12-25 Tue 11:41]--[2012-12-25 Tue 12:21] =>  0:39
CLOCK: [2012-12-19 Wed 11:52]--[2012-12-19 Wed 12:34] =>  0:41
CLOCK: [2012-12-15 Sat 16:46]--[2012-12-15 Sat 17:35] =>  0:49
CLOCK: [2012-12-10 Mon 17:15]--[2012-12-10 Mon 18:00] =>  0:45
CLOCK: [2012-12-02 Sun 16:18]--[2012-12-02 Sun 17:05] =>  0:47
:END:
:PROPERTIES:
:STYLE: habit
:REPEAT_TO_STATE: NEXT
:ID: d52c3978-eea8-457c-b9c9-1a38d6d54a88
:LAST_REPEAT: [2013-01-28 Mon 18:10]
:END:
** New value
SCHEDULED: <2013-01-30 Wed .+4d/5d>
    - State "DONE"       from "NEXT"       [2013-01-26 Sat 18:10]
    - State "DONE"       from "NEXT"       [2013-01-22 Tue 19:24]
    - State "CANCELLED"  from "NEXT"       [2013-01-15 Tue 09:55] \\
      Sick
    - State "DONE"       from "NEXT"       [2013-01-12 Sat 16:23]
    - State "CANCELLED"  from "NEXT"       [2013-01-07 Mon 12:58] \\
      Too much pain.
    - State "DONE"       from "NEXT"       [2012-12-29 Sat 11:47]
    - State "DONE"       from "NEXT"       [2012-12-25 Tue 12:22]
    - State "DONE"       from "NEXT"       [2012-12-19 Wed 12:35]
    - State "DONE"       from "NEXT"       [2012-12-15 Sat 17:35]
    - State "DONE"       from "NEXT"       [2012-12-10 Mon 18:04]
    - State "CANCELLED"  from "NEXT"       [2012-12-06 Thu 09:56] \\
      Was too tired
    - State "DONE"       from "NEXT"       [2012-12-02 Sun 19:47]
    - State "DONE"       from "NEXT"       [2012-11-22 Thu 10:34]
    - State "DONE"       from "NEXT"       [2012-11-18 Sun 09:59]
:LOGBOOK:
CLOCK: [2013-01-30 Wed 08:50]--[2013-01-30 Wed 09:26] =>  0:35
CLOCK: [2012-12-29 Sat 11:10]--[2012-12-29 Sat 11:35] =>  0:24
CLOCK: [2012-12-25 Tue 11:41]--[2012-12-25 Tue 12:21] =>  0:39
CLOCK: [2012-12-19 Wed 11:52]--[2012-12-19 Wed 12:34] =>  0:41
CLOCK: [2012-12-15 Sat 16:46]--[2012-12-15 Sat 17:35] =>  0:49
CLOCK: [2012-12-10 Mon 17:15]--[2012-12-10 Mon 18:00] =>  0:45
CLOCK: [2012-12-02 Sun 16:18]--[2012-12-02 Sun 17:05] =>  0:47
:END:
:PROPERTIES:
:STYLE: habit
:REPEAT_TO_STATE: NEXT
:ID: d52c3978-eea8-457c-b9c9-1a38d6d54a88
:LAST_REPEAT: [2013-01-28 Mon 18:10]
:END:
** End of edit



* Body was changed in MobileOrg and on the computer F(edit:body) [[id:d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9][Give talk on Brendle's proof of Lawson conjecture]]
  :PROPERTIES:
  :ID:       1e46659c-408c-48fc-ac1a-c2ff61ada575
  :END:
** Old value
:LOGBOOK:
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** New value
:LOGBOOK:
CLOCK: [2013-01-30 Wed 09:42]--[2013-01-30 Wed 09:57] =>  0:14
  CLOCK: [2013-01-22 Tue 19:21]--[2013-01-22 Tue 20:07] =>  0:45
  CLOCK: [2013-01-22 Tue 16:16]--[2013-01-22 Tue 17:14] =>  0:57
  :END:
  :PROPERTIES:
    :ID:       d0caa6d9-cd5a-47ff-a7f7-25cd1e2a85f9
    :END:
[2012-11-27 Tue 13:13]
Speaker: Paul Bryan
Home Institution: UCSD
Date: 31 Jan 2013
Seminar Name: Differential Geometry
Title: Brendle's Proof of the Lawson Conjecture
Start Time: 10 am
Location: AP&M 7218
Abstract: In 1970, Lawson conjectured that the only embedded minimal torus in $S^3$ is the Clifford torus. Recently using a non-collapsing technique developed by Ben Andrews, Simon Brendle was able to give an affirmative answer to this question. I'll discuss the non-collapsing ideas and how they lead to Brendle's proof of the Lawson conjecture.
** End of edit

