#+FILETAGS: REFILE
* TODO Reading papers procedure
  :LOGBOOK:
  CLOCK: [2016-05-16 Mon 16:43]--[2016-05-16 Mon 16:51] =>  0:08
  :END:
[2016-05-16 Mon 16:43]

Develop a procedure for reading papers.

- A bib ref must be created along with a notes org headline. 
- Write scripts to organise papers by (relative paths so Dropbox doesn't de-reference) symlinks with title, author, keywords perhaps and MR subject. All papers will be stored in the papers directory (master pool)
- Tags to find them - is this managable if there are lots of tags, or should they be stored as keywords in a properties container?
- Any notes I write down should be added to the refs and any reviews also added there.
- Publish to the web in a non-advertised place on my website with links to dropbox. Add search by tags, author etc. to this page
- Work on the automatic scripts useds to create bib and notes entries along with downloading the paper
- When away from computer, takes notes and record URL's etc. somehow. Then at office, organise them properly using the system and clean up after.
* TODO Set up dropbox on phablet
[2016-05-16 Mon 17:26]
* TODO Set check_uncommited.sh to check git repositories as well
  SCHEDULED: <2016-06-20 Mon>
  :LOGBOOK:
  CLOCK: [2016-05-16 Mon 17:37]--[2016-05-16 Mon 17:38] =>  0:01
  :END:
[2016-05-16 Mon 17:37]
[[file:~/org/workflow.org::*Weekly%20Review][Weekly Review {14/16}]]
* TODO Org-mode repeating task jump to next week
  :LOGBOOK:
  CLOCK: [2016-05-16 Mon 17:40]--[2016-05-16 Mon 17:42] =>  0:02
  :END:
[2016-05-16 Mon 17:40]

Check how to change habits, reviews etc. to jump to next Monday, or next day and not add one week to previous completion date.
e.g. if it was last done on 1/1/2016, but today is the 13/3/2016 and I mark it as done, I want the next repeat to be the 14/3/2016 (if one day), or the next Monday if weekly
