#+FILETAGS: REFILE
* TODO Study tubular map
  :LOGBOOK:
  CLOCK: [2013-12-10 Tue 07:36]--[2013-12-10 Tue 07:37] =>  0:01
  :END:
  :PROPERTIES:
  :ID:       251ca587-000d-45ea-97d6-9d72bc19586f
  :END:
[2014-03-10 Mon 07:36]
- This is the map along the normal direction to a hypersurface. The cut point is where the map hits another point on the surface.
- How does this relate to cohomology of the normal bundle, the Poincare dual, and the Thom isomorphism. How does this cohomology evolve?
* TODO Non-collapsing in manifolds
  :LOGBOOK:
  CLOCK: [2013-12-10 Tue 07:37]--[2013-12-10 Tue 07:40] =>  0:03
  :END:
  :PROPERTIES:
  :ID:       cb506bf4-f2d9-4082-95fd-b717e75047d3
  :END:
[2014-03-10 Mon 07:37]
Given $M\subset N$ a cooriented hypersurface with normal vector $\nor$, define the cooriented (oriented?) curvature tangent ball at $p$ to be the largest ball tangent to $M$ with center in the direction $\nor$. Now do variations to find a viscosity equation for the curvature.
* TODO Register Devon on club penguin
  :PROPERTIES:
  :ID:       b09d53be-dfb5-4aa0-b4dc-c4b9de5fdff0
  :END:
[2013-12-13 Fri 21:21]
* TODO Investigate morhpisms of forms
  :PROPERTIES:
  :ID:       bcad8d1d-61fa-4614-9662-8f264d9ae1e4
  :END:
- Often these are given by the wedge of some form. Is there some way to characterize such morphisms?
* TODO Archive things
  :PROPERTIES:
  :ID:       a1611ad9-0546-41d7-a584-9edb3ef77445
  :END:
[2014-01-02 Thu 18:44]
- Set up archiving for org-mode
- archive working files for faster check_uncommited
* TODO Note down book ideas
  :LOGBOOK:
  CLOCK: [2014-01-03 Fri 10:59]--[2014-01-03 Fri 11:02] =>  0:03
  :END:
  :PROPERTIES:
  :ID:       e0801755-e7b5-4eb4-92df-452668c17611
  :END:
[2014-01-03 Fri 10:59]
** Chemical X
Combustrum, aether, dark matter, vitamin X etc. are all examples of where people have postulated exotic unknown substances to explain poorly understood phemomena. Survey the history and give contemperary examples along with some reasons why we do this (anthropological?) 

** Cause and Effect
What is it? How do we get a handle on it? How do we reduce it from say the cause of an effect was everything in the backwards light cone (i.e. the state of the system at all times prior)?
* TODO Add collate scribbles to weekly review
  :LOGBOOK:
  CLOCK: [2014-01-06 Mon 17:11]--[2014-01-06 Mon 17:12] =>  0:01
  :END:
[2014-01-06 Mon 17:11]
Should create typing tasks from scribbles and schedule them 
* TODO Note down Einstein quote
  :LOGBOOK:
  CLOCK: [2014-01-06 Mon 17:12]--[2014-01-06 Mon 17:13] =>  0:01
  :END:
[2014-01-06 Mon 17:12]
[2] p. vi Sharpe, Diff. Geo.
* DONE Add TA's to Ted
  DEADLINE: <2014-01-22 Wed>
  :LOGBOOK:
  - State "DONE"       from "NEXT"       [2014-01-22 Wed 15:48]
  CLOCK: [2014-01-22 Wed 15:39]--[2014-01-22 Wed 15:48] =>  0:09
  CLOCK: [2014-01-22 Wed 14:10]--[2014-01-22 Wed 14:11] =>  0:01
  :END:
[2014-01-22 Wed 14:10]
