#+FILETAGS: REFILE
* TODO Contact Pain Away
  :LOGBOOK:
  :END:
[2013-03-25 Mon 21:09]

* TODO Organise garden
  :LOGBOOK:
  :END:
[2013-03-25 Mon 21:09]
* TODO Farming research
  :LOGBOOK:
  CLOCK: [2013-03-25 Mon 21:09]--[2013-03-25 Mon 21:10] =>  0:01
  :END:
[2013-03-25 Mon 21:09]
Look into how I'll set up my farm. Prices for livestock for instance is relevant. Also, plans for chook runs and pig runs and info on raising cows. Find out hardware prices also.
* TODO Research Geometric Measure Theory/Geometric Integration Theory
  :LOGBOOK:
  CLOCK: [2013-03-26 Tue 13:44]--[2013-03-26 Tue 13:47] =>  0:03
  :END:
[2013-03-26 Tue 13:44]

Leon Simon
Whitney
Federer, Fleming
Almgren
Evans - measure theory
BV functions - Di Giorgio
Krantz
* TODO Solitions and ancient solutions
  :LOGBOOK:
  CLOCK: [2013-03-26 Tue 13:47]--[2013-03-26 Tue 13:49] =>  0:02
  :END:
[2013-03-26 Tue 13:47]
Can we come up with an energy for ancient solutions? Something like the first derivative of curvature then look at minimisers? Are they ancient? We should also get some monotone quantity under the flow. Then we need to characterise the stationary solutions.
Is Angenent Oval a soliton?

