#+FILETAGS: REFILE


* TODO Pay Ben Chow $180
  CLOCK: [2012-10-17 Wed 08:22]--[2012-10-17 Wed 08:22] =>  0:00
[2012-10-17 Wed 08:22]
* TODO Contact Ben Andrews about MCF, geometric evolution eqn's books
  CLOCK: [2012-10-17 Wed 08:23]--[2012-10-17 Wed 08:23] =>  0:00
[2012-10-17 Wed 08:23]
* TODO Research ancient soln's
See Hamilton, Sessum, Daskopolus and Ben Chow's exposition
  CLOCK: [2012-10-17 Wed 08:23]--[2012-10-17 Wed 08:24] =>  0:01
[2012-10-17 Wed 08:23]
* TODO Do UCSD required courses
Sexual harassment, something else?
  CLOCK: [2012-10-17 Wed 09:47]--[2012-10-17 Wed 09:48] =>  0:01
[2012-10-17 Wed 09:47]
* TODO Get homework scores
[[https://docs.google.com/a/ucsd.edu/spreadsheet/ccc?key=0AlsrGAe5FGyBdGR3T29ERERzMm44LTRoU3R2bU13RkE&invite=CNuWms4G][Fall Math 150A]]
  CLOCK: [2012-10-18 Thu 10:44]--[2012-10-18 Thu 10:44] =>  0:00
[2012-10-18 Thu 10:44]

* TODO Update office hours
  CLOCK: [2012-10-18 Thu 10:45]--[2012-10-18 Thu 10:45] =>  0:00
[2012-10-18 Thu 10:45]
To all Instructional Faculty and TAs for Fall 2012 (please note the correctly working links to office hour information);

It's that time of the quarter when we ask you to submit office hours to the front desk.  We are continuing with our on-line submission form that interacts with the departmental webpages, listing office hours at either
http://math.ucsd.edu/people/office-hours-instructors/
for Faculty
or
http://math.ucsd.edu/people/office-hours-tas/
for TAs


To submit your office hours:

  1. Go to web site: http://mathlink.ucsd.edu/

  2. Enter YOUR Euclid username and password and click on the login button

  3. Click the Office Hours icon

  4. A list with all your Fall 2012 courses will be presented

  5. Select one of the courses by pressing 'Edit'

  6. Fill out the days and hours for your primary office hours and any additional office hours you will be holding for each course.

  7. Logout when finished

If you have difficulties with the system, please feel free to email me your hours - along with any suggestions for improving the submission system.

Thank you,
Scott

-------------------------
Scott Rollans
Undergraduate Program Officer
UCSD Mathematics
* TODO Read kp newsletter
[[http://kaiserpermanente-mail.org/14e102af8layfousiaj5hioyaaaaaa2j4zxwaqctfoqyaaaaa/C?V=bF9pbmRleAEBcHJvZmlsZV9pZAExNzY1NTkyNTU2AUZSU1RfTk0BUEFVTAF6aXBfY29kZQEBX1dBVkVfSURfATEzNDg5OTA2MAFfUExJU1RfSURfATc3NzAyNTkBZ19pbmRleAEBZW1haWxfYWRkcgFwYWJyeWFuQGdtYWlsLmNvbQFfU0NIRF9UTV8BMjAxMjEwMTYxMTAwMDABcHJvZmlsZV9rZXkBNTUwMDAxNDg2MjgyMg%3D%3D&hfRgPQxxOsF3fqchSPOhjw][newsletter]]
  CLOCK: [2012-10-18 Thu 10:46]--[2012-10-18 Thu 10:46] =>  0:00
[2012-10-18 Thu 10:46]
* TODO Call KP membership
Need to find out what to do when sick or in an emergency
  CLOCK: [2012-10-18 Thu 10:46]--[2012-10-18 Thu 10:47] =>  0:01
[2012-10-18 Thu 10:46]
* TODO Setup mercurial sync and fetch
  CLOCK: [2012-10-18 Thu 10:59]--[2012-10-18 Thu 10:59] =>  0:00
[2012-10-18 Thu 10:59]
