#+FILETAGS: REFILE
* TODO Study non-smooth mean curvature flow, minimal surfaces via support fn
  :LOGBOOK:
  CLOCK: [2013-10-19 Sat 15:33]--[2013-10-19 Sat 15:34] =>  0:01
  :END:
  :PROPERTIES:
  :ID:       7fa8e994-7da5-4bf8-bae3-000740c3e966
  :END:
[2013-10-19 Sat 15:33]
- Surely I can get something out of this? Maybe I can get regularity results? 
- Also, high co-dimension should be interesting. The support function is the projection onto the normal bundle here.

* TODO Check out food sources
  SCHEDULED: <2013-11-03 Sun>
  :LOGBOOK:
  CLOCK: [2013-10-20 Sun 11:06]--[2013-10-20 Sun 11:07] =>  0:01
  :END:
[2013-10-20 Sun 11:06]

- Cow pooling: http://www.marksdailyapple.com/cowpooling/#axzz2iHnvc1H3
- Urban foraging

* TODO Check concavity
  SCHEDULED: <2013-10-21 Mon>
  :LOGBOOK:
  CLOCK: [2013-10-20 Sun 20:15]--[2013-10-20 Sun 20:19] =>  0:04
  :END:
[2013-10-20 Sun 20:15]
For the hyperbolic barrier, concavity should fail when $b$ is too large. For how large, see D of 20/10 notes.

I have a lower bound for the numerator. To get an upper bound for the denominator for large x, take x around 1000 and add little bit. Then I just choose $b$ larger than the quotient and I should lose concavity.
