#+FILETAGS: REFILE
* TODO Check textbooks for teaching DG
  :LOGBOOK:
  :END:
  :PROPERTIES:
  :ID:       8812eda3-cf7b-4f6e-8e56-b3ea5eead235
  :END:
[2013-02-25 Mon 10:13]
See email from worldscientific4@mail3.wspc.com
* TODO Publish single org-mode file to multiple page html
  :LOGBOOK:
  CLOCK: [2013-02-28 Thu 17:57]--[2013-02-28 Thu 17:58] =>  0:01
  :END:
  :PROPERTIES:
  :ID:       9d87b9bb-023a-4250-82af-664d14953320
  :END:
[2013-02-28 Thu 17:57]
I can export to Docbook, then use standard tools to produce mutli-page html and single page html files. Can I just do this in one go?
* TODO Tag someday projects as SOMEDAY and use a filter to remove them from agenda
  :LOGBOOK:
  CLOCK: [2013-02-28 Thu 21:51]--[2013-02-28 Thu 21:52] =>  0:01
  :END:
  :PROPERTIES:
  :ID:       9ab0346c-4212-4d5c-8b5b-594ce1312a1b
  :END:
[2013-02-28 Thu 21:51]

* TODO Tag papers in ref.org so I can find papers by subject!
  :LOGBOOK:
  CLOCK: [2013-03-01 Fri 13:57]--[2013-03-01 Fri 14:00] =>  0:03
  :END:
  :PROPERTIES:
  :ID:       fd828213-33b7-4ebd-9292-b1323dd3baff
  :END:
[2013-03-01 Fri 13:57]
I could also have author, title, date etc. in the properties drawer! This is redundant, but means I can search my org file on author etc.
No! Maybe I can use reftex and get it to take me to the entry in refs.org? I can certainly due this manually, using reftex to take me to the bib file which gives the ID which I can search for in the org file. Then I don't need to maintain duplicate info in the org and bib files and have all the power of reftex available.
* TODO Update exercise habits
  :LOGBOOK:
  CLOCK: [2013-03-04 Mon 08:36]--[2013-03-04 Mon 08:39] =>  0:03
  :END:
  :PROPERTIES:
  :ID:       2b46623b-23ae-448b-be01-9e99412a4fb9
  :END:
[2013-03-04 Mon 08:36]

Habit should just be exercise, possibly also morning mobility, evening decompression
Exercise is daily, the other two can be 1-2 days each.
* TODO Put org-mobile code into one function
  :LOGBOOK:
  :END:
  :PROPERTIES:
  :ID:       503b6139-d929-4ab7-a264-ff52b1c00420
  :END:
[2013-03-14 Thu 14:05]
* TODO Learn agenda views
  :LOGBOOK:
  :END:
[2013-03-18 Mon 16:03]
If I'm working on a project, I want an agenda view showing me just that project.
* TODO Sort out reading list
  :LOGBOOK:
  CLOCK: [2013-03-19 Tue 11:20]--[2013-03-19 Tue 11:22] =>  0:02
  :END:
[2013-03-19 Tue 11:20]
This should be a place where I put links to articles, books, emails etc. They can be tagged of course. Should I also have a paper folder for things like journals, magazines etc.? The archive is of course something else that should go here. It might be nice to link this with newsreader capabilities too.
