#+FILETAGS: REFILE
* TODO Change course web template
  :LOGBOOK:
  CLOCK: [2013-09-22 Sun 12:41]--[2013-09-22 Sun 12:42] =>  0:01
  :END:
  :PROPERTIES:
  :ID:       dcc43349-f461-44f9-9403-cf87843bc238
  :END:
[2013-09-22 Sun 12:41]
Remove sidebar

* TODO Goals in agenda
  :LOGBOOK:
  CLOCK: [2013-09-30 Mon 21:15]--[2013-09-30 Mon 21:16] =>  0:01
  :END:
  :PROPERTIES:
  :ID:       24d2f2f3-4ced-4723-8502-2d6c4e705900
  :END:
[2013-09-30 Mon 21:15]
Add goals to agenda to remind myself each day. E.g. work, diet, exercise, general things like be patient, don't over-explain things etc.
* TODO Course announcements
  :PROPERTIES:
  :ID:       9e7a5c58-45a7-4595-8a0d-e2765a9cf466
  :END:
[2013-09-30 Mon 21:24]
- updated calendar
- solns to homework posted on TA's (ali) website
* TODO Setup some agenda filter macros
  :PROPERTIES:
  :ID:       b7060562-fc53-44b0-8f52-d84dce4c177f
  :END:
[2013-10-01 Tue 10:23]
want to hit a key so that only work tasks are shown or only personal/family tasks are shown
* TODO Get personal desktop launcher files in VC
  SCHEDULED: <2013-10-04 Fri>
  :LOGBOOK:
  CLOCK: [2013-10-04 Fri 11:34]--[2013-10-04 Fri 11:35] =>  0:01
  :END:
[2013-10-04 Fri 11:34]
- I want to add a launcher to my panel for custom cmds and already have a launcher written, but can't access it from work. Putting it in VC will solve that problem.
