#+FILETAGS: WARWICK

* Data
- Id: 1571708
** Codes
1. 254 851 54	6.	554 310 95
2.	622 904 15	7.	282 065 39
3.	936 222 63	8.	588 296 32
4.	291 829 46	9.	475 517 96
5.	235 612 92	10.	613 810 60
* Teaching
** Courses
*** 2016
**** Spring
***** DONE MA4C0
      :LOGBOOK:
      - State "DONE"       from "TODO"       [2016-06-15 Wed 14:04]
      :END:
****** Final Exam
       <2016-05-26 Thu 09:30--13:00>
       :PROPERTIES:
       :Location: Rootes Restaurant Area
       :END:

****** DONE Grade exams
       DEADLINE: <2016-06-05 Sun>
       :LOGBOOK:
       - State "DONE"       from "NEXT"       [2016-06-15 Wed 14:04]
       :END:
* Research
** Grant
- Acknowledgement: This research has been supported by the EPSRC on a Programme Grant entitled ‘Singularities of Geometric Partial Differential Equations’ reference number EP/K00865X/1
* Seminars
** Analysis Seminar
*** Summer
**** Dan Ketovar: Sharp entropy bounds of closed surfaces and min-max theory.
     <2016-06-16 Thu 14:00-15:00>
     :PROPERTIES:     
     :location: MS.05
     :END:

- Abstract:
  In 2010, Colding-Ilmanen-Minicozzi-White conjectured that the entropy of any closed surface in R^3 is at least that of the self-shrinking two-sphere.  I will explain joint work with X. Zhou where we interpret this conjecture as a parabolic version of the Willmore problem and give a min-max proof of (most cases) of their conjecture.

**** Panagiota Daskalopoulos: Ancient solutions to geometric flows
     <2016-06-16 Thu 16:00-17:00>
     :PROPERTIES:
     :location: B3.02
     :END:

**** Sigurd Angenent: Mean curvature flow from cones, and other sources of non uniqueness in MCF
<2016-06-23 Thu 14:30-15:30>
     :PROPERTIES:
     :location: B3.02
     :END:

***** Abstract
Self similar shrinking solutions to Mean Curvature Flow with conical ends are completely determined by their asymptotic cone at infinity, due to a result of Lu Wang.  In contrast, there exist older examples of cones that admit more than one smooth expanding self similar evolution by MCF.  In this talk I will exhibit examples of smooth cones that admit many more smooth solutions by MCF, most of which are not self similar.

**** Spyros Alexakis: Singularity formation in Black hole interiors.
<2016-06-23 Thu 16:00-17:00>
     :PROPERTIES:
     :location: B3.02
     :END:

***** Abstract
The prediction that solutions of the Einstein equations in the interior of black holes must always terminate at a singularity was originally conceived by Penrose in 1969, under the name of “strong cosmic censorship hypothesis”. The nature of this break-down (i.e. the asymptotic properties of the space-time metric as one approaches the terminal singularity) is not predicted, and remains a very hotly debated question to this day. One key question is the causal nature of the singularity (space-like, vs null for example). Another is the rate of blow-up of natural physical/geometric quantities at the singularity. Mutually contradicting predictions abound in this topic. Much work has been done under the assumption of spherical symmetry (for various matter models). We present recent developments (partly due to the speaker and G. Fournodavlos) which go well beyond this restrictive class. A key role is played by the axial symmetry reduction of the Einstein equations, where a wave map structure appears.

