#+FILETAGS: WRITING

* TODO Out of Life's Way
  :PROPERTIES:
  :ID:       096c42be-9d2b-4703-a22e-cdeed293f729
  :END:
** NEXT Transcribe from Bei Da notebook
   :PROPERTIES:
   :ID:       1eb48606-3138-42fa-967f-a4379032c837
   :END:
* TODO Lying on the grass
  :PROPERTIES:
  :ID:       32361036-e967-4245-aac0-e486c6e0cb27
  :END:
** NEXT Transcribe from Bei Da notebook
   :PROPERTIES:
   :ID:       6eff07e2-11a0-4f21-b1de-05ef97149947
   :END:

* TODO Daoist magic dudes
  :PROPERTIES:
  :ID:       d2337c89-b25e-4c19-bdb7-f729f9bfde6c
  :END:
These guys train up their Qi. They root to the earth. Perhaps at some battle a (big?) guy defends the monastary while the others get away and root himself deep into the earth, literally. I might also have this daoist guy who is really old and who casually walks very fast without seeming to put any effort into it. They do big jumps, train iron shirt and so on. I should have hand seals and chanting in it also.

They also channel Qi of course through their Dan Tians up through the Ren channel and down thru the Du channel, the circle being the Micocosmic circle. The energy transforms from gas to fluid to solid upon a monks enlightenment. Perhaps the bad guys are taking out monks, cremating them and then collecting the Xie Li Zi crystals that are left amongst the ashes. These they use for power some how.

** Refs
The QiGong year, Michael Bruney.
* TODO Abstract thought
  :PROPERTIES:
  :ID:       d303c5d0-59ab-409c-ada9-f755c398bb55
  :END:
- Defining property of humans (write on this too!)
- Too much abstract thought, don't notice Saber tooth
- Like attracts like
  - man & women discuss abstract ideas
  - spending time together + sexual desires leads to breeding (if sexual desires aren't satiated elsewhere, the need can overcome any lack of attraction, c.f. sailors on long voyages)
  - Fit, attractive people don't have any connection and so don't mix -> leads to jocks and nerds!
  - So abstract thought becomes prized in some and selection is for that thought -> increased abstract thought over time

